### ISSUE TITLE
Missing dependency in the Debian package

### ISSUE THREAD

**Issue by RonnyB74** [mfat/tvhplayer#3]
The debian package still lacks the dependency on the "tkinter" module, which is provided by the "python3-tk" package.

**Comment by mfat** [comment]
Thanks for flagging this. Will fix. Please share your impressions too.

**Comment by mfat** [comment]
@RonnyB74 I just tested the deb package on Ubuntu and it doesn't depend on python3-tk. Did you install the latest version (3.5)?

**Comment by RonnyB74** [comment]
If the package is not installed, the tvhplayer 3.5 cannot be started.

**Comment by mfat** [comment]
I ran 
`sudo apt remove python3-tk`
and then uninstalled tvhplayer.
Then reinstalled it using `dpkg -i` and it started successfully. Can you please post any error message when you start tvhplayer from the commandline?

**Comment by RonnyB74** [comment]
Without this package the following error message was displayed:

`:~$ tvhplayer 
Traceback (most recent call last):
  File "/usr/bin/tvhplayer", line 33, in <module>
    sys.exit(load_entry_point('tvhplayer==3.5', 'console_scripts', 'tvhplayer')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/tvhplayer", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/tvhplayer/tvhplayer.py", line 3, in <module>
    from tkinter.filedialog import FileDialog
ModuleNotFoundError: No module named 'tkinter'`

**Comment by mfat** [comment]
@RonnyB74 Encountered the same issue on Debian testing. I'll fix.
